BookingMVC/Controllers/RoomController.cs
using BookingMVC.Common;
using BookingMVC.Common.Logger;
using BookingMVC.Filters;
using BookingMVC.Models;
using BookingMVC.Repositories;
using BookingMVC.Services.ContractsServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingMVC.Controllers
{
    [Authentication]
    public class RoomController : Controller
    {
        private readonly IHistoryService _historyService;
        private readonly IPhotoService _photoService;
        private readonly IRoomBookingService _roomBookingService;
        private readonly IRoomService _roomService;
        private readonly IUnitService _unitService;
        private readonly IRatingService _ratingService;
        private readonly IUserService _userService;
        private readonly ILogBase _logBase;
        private readonly ILogFactory _logFactory;

        public RoomController(IHistoryService service,IPhotoService photoService,IRoomBookingService roomBookingService,IRoomService roomService,IUnitService unitService,IRatingService ratingService, IUserService userService, ILogFactory logFactory)
        {
            _historyService = service;
            _photoService = photoService;
            _roomBookingService = roomBookingService;
            _roomService = roomService;
            _unitService = unitService;
            _ratingService = ratingService;
            _userService = userService;
            _logFactory = logFactory;
            _logBase = logFactory.GetLogger(LoggerType.Database);
        }
        // GET: Room
        /// <summary>
        /// Get all rooms available foreach Unit
        /// </summary>
        /// <param name="id"> UnitId </param>
        /// <param name="dateFrom"> Check-in Date </param>
        /// <param name="dateTo"> Check-out Date</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index(int id)
        {
            RoomIndexModel roomIndexModel = new RoomIndexModel();
            var ratingModelList = new List<RatingModel>();
            DateTime? dateFrom = (DateTime?)Session["DateFrom"];
            DateTime? dateTo = (DateTime?)Session["DateTo"];

            if (dateFrom.HasValue && dateTo.HasValue)
            {
                roomIndexModel.Rooms = _roomService.GetFreeRooms(dateFrom, dateTo, id);
                Session.Remove("DateFrom");
                Session.Remove("DateTo");
                ViewBag.DateFrom = dateFrom;
                ViewBag.DateTo = dateTo;
            }
            else
            {
                roomIndexModel.Rooms = _roomService.GetRooms(id);
            }

            roomIndexModel.Photos = _photoService.DisplayPhoto(id, PhotoType.Hotel);
            var ratings = _ratingService.GetByUnit(id);
            foreach (var rating in ratings)
            {
                var userName = _userService.GetNameById(rating.UserId);
                var ratingModel = new RatingModel
                {
                    Date = rating.Date,
                    Details = rating.Details,
                    BookingId = rating.BookingId,
                    UserId = rating.UserId,
                    Value = rating.Value,
                    UserName = userName
                };

                ratingModelList.Add(ratingModel);
            }
            roomIndexModel.Ratings = ratingModelList;
            var average = _ratingService.GetAverage(id);
            roomIndexModel.Average = string.Format("{0:0.0}", average);
            roomIndexModel.UnitName = _unitService.GetNameById(id);
            return View(roomIndexModel);
        }

        [HttpPost]
        public ActionResult Index(DateTime? dateFrom,DateTime? dateTo,int? id)
        {
            var average = _ratingService.GetAverage(id.GetValueOrDefault());
            RoomIndexModel roomIndexModel = new RoomIndexModel
            {
                Rooms = _roomService.GetFreeRooms(dateFrom, dateTo, id),
                Photos = _photoService.DisplayPhoto(id.GetValueOrDefault(), PhotoType.Hotel),
                Average = string.Format("{0:0.0}", average),
                Ratings = _ratingService.GetByUnit(id.GetValueOrDefault())
            };
            roomIndexModel.UnitName = _unitService.GetNameById(id.GetValueOrDefault());
            return View(roomIndexModel);
        }

        /// <summary>
        /// Get pictures of rooms
        /// </summary>
        /// <param name="subjectId"> Id of Units or Rooms</param>
        /// <returns></returns>
        public ActionResult Picture(int subjectId)
        {
            ViewBag.subjectId = subjectId;
            RoomPictureModel roomPictureModel = new RoomPictureModel();
            roomPictureModel.Photos = _photoService.DisplayPhoto(subjectId, Common.PhotoType.Room);
            roomPictureModel.RoomNr = _roomService.GetRoomNr(subjectId);
            return View(roomPictureModel);
        }
        
        [HttpGet]
        public ActionResult Book(int roomId)
        {
            ViewBag.RoomId = roomId;
            return View();
        }

        /// <summary>
        /// Book a room
        /// </summary>
        /// <param name="roomBookingModel"></param>
        /// <param name="roomId"></param>
        /// <param name="historyModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Book(RoomBookingModel roomBookingModel, int roomId, HistoryModel historyModel)
        {
            try
            {
                User user = (User)Session["User"];
                roomBookingModel.UserId = user.Id;
                historyModel.RoomId = roomId;
                historyModel.UserId = user.Id;
                roomBookingModel.RoomId = roomId;
                _roomBookingService.BookARoom(roomBookingModel);
                _historyService.RoomHistory(historyModel);
                ViewBag.Success = "Room Booked";
                return View(roomBookingModel);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = $"Error : {ex.Message}";
                _logBase.Error(ex.Message,ex.StackTrace);
                return View(roomBookingModel);
            }
        }
        
        [HttpGet]
        public ActionResult Edit(int roomId)
        {
            ViewBag.RoomId = roomId;
            var room = _roomService.GetById(roomId);
            var roomModel = new RoomModel
            {
                Details = room.Details,
                NrPersons = room.NrPersons,
                Price = room.Price,
                RoomNr = room.RoomNr,
                Type = room.Type,
                UnitId = room.UnitId
            };

            return View(roomModel);
        }
        
        [HttpPost]
        public ActionResult Edit(RoomModel roomModel, int roomId)
        {
            ViewBag.RoomId = roomId;
            try
            {
                _roomService.Edit(roomModel, roomId);
                ViewBag.Message = "Saved";
                return View(roomModel);
            }
            catch (Exception e)
            {
                ViewBag.Error = $"Error: {e.Message}";
                return View(roomModel);
            }
        }
        
        [HttpGet]
        public ActionResult AddPhoto(int roomId)
        {
            ViewBag.RoomId = roomId;
            return View();
        }
        
        [HttpPost]
        public ActionResult AddPhoto(int roomId,IEnumerable<HttpPostedFileBase> files)
        {
            try
            {
                foreach (var file in files)
                {
                    _photoService.AddPhoto(file, PhotoType.Room, roomId);
                }
                ViewBag.Message = ($"{files.Count()} photos uploaded successfully");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = $"Error : {e.Message}";
            }
            return View();
        }

        /// <summary>
        /// Delete a room
        /// </summary>
        /// <param name="roomId"></param>
        /// <param name="unitId"> UnitId </param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(int roomId,int unitId)
        {
            _roomService.Delete(roomId);
            return RedirectToAction("Index", new { id = unitId});
        }
    }
}

BookingMVC/Controllers/UnitController.cs
using BookingMVC.Common;
using BookingMVC.Common.Logger;
using BookingMVC.Models;
using BookingMVC.Repositories;
using BookingMVC.Repositories.Contracts;
using BookingMVC.Services.ContractsServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingMVC.Controllers
{
    public class UnitController : Controller
    {
        private readonly IRoomService _roomService;
        private readonly IUnitService _unitService;
        private readonly IPhotoService _photoService;
        private readonly IRatingService _ratingService;
        private readonly ILogBase _logBase;
        private readonly ILogFactory _logFactory;
        public UnitController(IRoomService roomService,IUnitService unitService, IPhotoService photoService, IRatingService ratingService, ILogFactory logFactory)
        {
            _roomService = roomService;
            _unitService = unitService;
            _photoService = photoService;
            _ratingService = ratingService;
            _logFactory = logFactory;
            _logBase = logFactory.GetLogger(LoggerType.File);
        }
        // GET: Unit
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UnitModel unitModel)
        {
            bool unitexists = _unitService.UnitExist(unitModel.Unit.Name);

            if (!unitexists)
            {
                try
                {
                    User user = (User)Session["User"];
                    unitModel.Unit.UserId = user.Id;
                    _unitService.Create(unitModel);
                    ViewBag.Message = "Success";
                    ModelState.Clear();
                    return View();
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = $"Error: {e.Message}";
                    _logBase.Error(e.Message,e.StackTrace);
                    return View(unitModel);
                }
            }
            else
            {
                ViewBag.MessageError = "This Unit already exists";
                return View();
            }
        }
        
        public ActionResult AddRoom(int unitId)
        {
            ViewBag.UnitId = unitId;
            return View();
        }
        
        [HttpPost]
        public ActionResult AddRoom(RoomModel roomModel,int unitId)
        {
            bool roomNrExists = _roomService.RoomNrExists(roomModel.RoomNr,roomModel.UnitId);

            if (!roomNrExists)
            {
                try
                {
                    ViewBag.UnitId = unitId;
                    _roomService.AddRoom(roomModel);
                    ViewBag.Message = "Successfuly added";
                    ModelState.Clear();
                    return View();
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = $"Error: {ex.Message}";
                    _logBase.Error(ex.Message,ex.StackTrace);
                    return View(roomModel);
                }
            }
            else
            {
                ViewBag.MessageError = "Room Number already exists";
                return View();
            }
            
        }
        
        [HttpGet]
        public ActionResult Edit(int unitId)
        {
            ViewBag.UnitId = unitId;
            var unit = _unitService.UnitById(unitId);
            var unitModel = new UnitModel
            {
                Unit = unit
            };
            return View(unitModel);
        }

        [HttpPost]
        public ActionResult Edit(UnitModel unitModel)
        {
            try
            {
                _unitService.Edit(unitModel);
                ViewBag.Message = "Saved";
                return View(unitModel);
            }
            catch(Exception e)
            {
                ViewBag.Error = $"Error: {e.Message}";
                return View(unitModel);
            }
        }
        
        [HttpGet]
        public ActionResult AddPhoto(int unitId)
        {
            ViewBag.UnitId = unitId;
            return View();
        }
        
        [HttpPost]
        public ActionResult AddPhoto(int unitId, IEnumerable<HttpPostedFileBase> files)
        {
            try
            {
                foreach (var file in files)
                {
                    _photoService.AddPhoto(file, PhotoType.Hotel, unitId);
                }

                ViewBag.Message = ($"{files.Count()} photos uploaded successfully");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = $"Error : {e.Message}";
            }
            return View();
        }
        
        [HttpGet]
        public ActionResult MyReviews(int userId)
        {
            ViewBag.UserId = userId;
            ReviewsHistoryModel model = new ReviewsHistoryModel();
            var reviews = _ratingService.GetByUser(userId);
            model.Ratings = reviews;
            return View(model);
        }

        
        [HttpGet]
        public ActionResult AddReview(int bookingId)
        {
            User user = (User)Session["User"];
            var userId = user.Id;
            ViewBag.RatingLimit = 5;
            ViewBag.BookingId = bookingId;
            return View();
        }
        
        [HttpPost]
        public ActionResult AddReview(RatingModel ratingModel,int bookingId)
        {
            try
            {
                User user = (User)Session["User"];
                ratingModel.UserId = user.Id;
                _ratingService.Add(ratingModel);

                ViewBag.Message = "Thank you for posting a review!";
            }
            catch(Exception e)
            {
                ViewBag.Error = $"Error : {e.Message}";
            }
            
            return View();
        }
        
        [HttpGet]
        public ActionResult EditReview(int id)
        {
            var ratingModel = new RatingModel();
            ViewBag.EditMode = true;
            ViewBag.RatingLimit = 5;
            var rating = _ratingService.GetById(id);
            if (rating != null)
            {
                ratingModel.Id = rating.Id;
                ratingModel.Details = rating.Details;
                ratingModel.BookingId = rating.BookingId;
                ratingModel.UserId = rating.UserId;
                ratingModel.Value = rating.Value.Value;
            }
            else
            {
                var reviews = _ratingService.GetByBooking(id);
                foreach (var review in reviews)
                {
                    ratingModel.Id = review.Id;
                    ratingModel.Details = review.Details;
                    ratingModel.BookingId = review.BookingId;
                    ratingModel.UserId = review.UserId;
                    ratingModel.Value = review.Value.Value;
                }
            }

            return View("AddReview", ratingModel);
        }
        
        [HttpPost]
        public ActionResult EditReview(RatingModel ratingModel)
        {
            try
            {
                ViewBag.EditMode = true;
                _ratingService.Edit(ratingModel);
                ViewBag.Message = "Saved";
            }
            catch (Exception e)
            {
                ViewBag.Error = $"Error: {e.Message}";;
            }
            return View("AddReview",ratingModel);
        }

        [HttpPost]
        public ActionResult DeleteReview(int id, int userId)
        {
            _ratingService.Delete(id);
            return RedirectToAction("MyReviews", new { userId = userId });
        }
    }
}

BookingMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BookingMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BookingMVC/Views/Home/Index.cshtml
@using BookingMVC.Repositories
@using BookingMVC.Common
@using BookingMVC.Models
@model UnitIndexModel
@{
    ViewBag.Title = "List of Units";
}

<br />
<h2><b> Welcome </b></h2>
<br />
@{
    var user = (User)Session["User"];
    if (user != null)
    {
        <input type="button" value="Feedback" onclick="location.href ='@Url.Action("Create", "Feedback", new { userId = user.Id, username = user.UserName })'" style="border-color:black; border-width:1px" />
        <input type="button" value="History" onclick="location.href ='@Url.Action("Show", "History", new { userId = user.Id })'" style="border-color:black; border-width:1px" />
        <input type="button" value="My Reviews" onclick="location.href= '@Url.Action("MyReviews", "Unit", new { userId = user.Id})'" style="border-color:black; border-width:1px" />
        if (user.Type == UserType.Administrator)

        {
            <input type="button" value="Users" onclick="location.href='@Url.Action("Index", "User")'" style="border-color:black; border-width:1px" />
            <input type="button" value="Logout" onclick="location.href= '@Url.Action("Logout", "Login")'" style="border-color:black; border-width:1px" />
            <input type="button" value="Feedback's List" onclick="location.href= '@Url.Action("Index", "Feedback")'" style="border-color:black; border-width:1px" />
        }
        else if (user.Type == UserType.RegularUser)
        {
            <input type="button" value="Logout" onclick="location.href= '@Url.Action("Logout", "Login")'" style="border-color:black; border-width:1px" />
            <input type="button" value="Add Unit" onclick="location.href='@Url.Action("Create", "Unit")'" style="background-color:orange; border-color:black; border-width:1px" />
            <input type="button" value="My Offers" onclick="location.href='@Url.Action("Offers", "Home", new { userId = user.Id })'" style="border-color:black; border-width:1px" />
        }
        else
        {

            <input type="button" value="Logout" onclick="location.href= '@Url.Action("Logout", "Login")'" style="border-color:black; border-width:1px" />

        }
    }

}
<fieldset>
    <legend style="text-align:center"><i>Units Available</i></legend>
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @if (@ViewBag.Message != null)
    {
        <div style="border: 1px solid red">
            @ViewBag.Message
        </div>
    }
    @ViewBag.Message

    @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { id = "searchform" }))
    {
        <b>
            Search Option:
            @Html.TextBox("Search", null, new { @class = "Search" })

            Check-In: @Html.TextBox("dateFrom", null, new { @class = "datepicker" })
            Check-Out: @Html.TextBox("dateTo", null, new { @class = "datepicker" })

            <input type="submit" name="submit" value="Search" />
        </b>
    }
    <br />

    <table class="table" style="background-color:#b2dbcb">
        @{ var unit = Model.Units.First();}
        <tr style="background-color:#2ea764">
            <th>@Html.DisplayNameFor(model => unit.Unit.Name)</th>
            <th>@Html.DisplayNameFor(model => unit.Unit.Type)</th>
            <th>@Html.DisplayNameFor(model => unit.Unit.Stars)</th>
            <th>@Html.DisplayNameFor(model => unit.Unit.Description)</th>
            <th>@Html.DisplayNameFor(model => unit.Unit.Address)</th>
            <th>@Html.DisplayNameFor(model => unit.Unit.Contact)</th>
            <th>@Html.DisplayNameFor(model => unit.Rating)</th>
            <th></th> <th></th>
            <th></th>
            <th> </th>
            <th></th>
        </tr>

        @ViewBag.Message

        @foreach (var item in Model.Units)
        {

            <tr>
                <td><b>@Html.DisplayFor(model => item.Unit.Name)</b></td>
                <td>@Html.DisplayFor(model => item.Unit.Type) </td>
                <td>@Html.DisplayFor(model => item.Unit.Stars)</td>
                <td>@Html.DisplayFor(model => item.Unit.Description)</td>
                <td>@Html.DisplayFor(model => item.Unit.Address)</td>
                <td>@Html.DisplayFor(model => item.Unit.Contact)</td>
                <td>@Html.DisplayFor(model => item.Rating)</td>
                <td><input type="button" value="Show Details" onclick="location.href='@Url.Action("Index", "Room", new { id = item.Unit.Id })'" /></td>
                @{
                    if (user != null)
                    {
                        if (user.Type == UserType.RegularUser)
                        {
                            <td> <input type="button" value="AddRoom" onclick="location.href= '@Url.Action("AddRoom", "Unit", new { unitId = item.Unit.Id })'" style="background-color:orange; border-color:black; border-width:1px" /></td>

                        }
                        else if (user.Type == UserType.Administrator)
                        {
                            <td>
                                <input type="button" value="Edit Unit" onclick="location.href='@Url.Action("Edit","Unit", new { unitId = item.Unit.Id })'" style="border-color:black; border-width:1px" />
                            <td> <input type="button" value="Add Photos" onclick="location.href= '@Url.Action("AddPhoto", "Unit", new { unitId = item.Unit.Id })'" border-color:black; border-width:1px" /> </td>
                            </td>

                            using (Html.BeginForm("Delete", "Home", FormMethod.Post))
                            {
                                <td><input type="hidden" name="unitId" value="@item.Unit.Id" /></td>
                                <td>
                                    <input type="submit" value="Delete Unit" style="border-color:black; border-width:1px" />
                                </td>
                            }
                        }
                    }

                }
            </tr>

        }

    </table>


    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    @section Scripts{
        <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
        <script>
            $(function () {
                $(".datepicker").datepicker().attr("autocomplete", "off");
            });
        </script>


        <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
        <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css"
              rel="Stylesheet" type="text/css" />
        <script src="~/Scripts/jquery-3.3.1.js"></script>
        <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
        <script type="text/javascript">
            $(function () {
                $("#Search").autocomplete({
                    source: function (request, response) {
                        $.ajax({
                            url: '../api/UnitAPI/GetUnits',
                            data: JSON.stringify(request.term),
                            dataType: "json",
                            type: "POST",
                            contentType: 'application/json; charset=utf-8',
                            success: function (data) {
                                response($.map(data, function (item) {
                                    return item.Name;
                                }))
                            },
                            error: function (response) {
                                alert(response.responseText);
                            },
                            failure: function (response) {
                                alert(response.responseText);
                            },
                        });
                    },
                })
            });
        </script>

        <script>

        </script>
    }
</fieldset>

BookingMVC/Views/Home/Offers.cshtml
@using BookingMVC.Repositories
@model IEnumerable<Unit>
@{
    ViewBag.Title = "Offers";
}

<h2>Your offers</h2>
<fieldset>
    @Html.AntiForgeryToken()

    <table class="table" style="background-color:#b2dbcb">
        <tr>
            <th style="background-color:#2ea764"> @Html.DisplayNameFor(model => model.Name)</th>
            <th style="background-color:#2ea764"> @Html.DisplayNameFor(model => model.Type)</th>
            <th style="background-color:#2ea764"> @Html.DisplayNameFor(model => model.Stars)</th>
            <th style="background-color:#2ea764"> @Html.DisplayNameFor(model => model.Description) </th>
            <th style="background-color:#2ea764">  @Html.DisplayNameFor(model => model.Address) </th>
            <th style="background-color:#2ea764"> @Html.DisplayNameFor(model => model.Contact)</th>
            <th style="background-color:#2ea764"></th>
            <th style="background-color:#2ea764"></th>
        </tr>
        @using (Html.BeginForm("Offers", "Home", FormMethod.Get))
        {
        }
        @ViewBag.Message
        @foreach (var item in Model)
        {
        <tr>
            <td><b>@Html.DisplayFor(model => item.Name)</b></td>
            <td>@Html.DisplayFor(model => item.Type)</td>
            <td>@Html.DisplayFor(model => item.Stars)</td>
            <td>@Html.DisplayFor(model => item.Description)</td>
            <td>@Html.DisplayFor(model => item.Address)</td>
            <td>@Html.DisplayFor(model => item.Contact)</td>
            <td><input type="button" value="See Rooms" onclick="location.href='@Url.Action("Index", "Room", new { id = item.Id })'" /></td>
            <td> <input type="button" value="Add Photos" onclick="location.href= '@Url.Action("AddPhoto", "Unit", new { unitId = item.Id })'" border-color:black; border-width:1px" /> </td>
        </tr>

        }

    </table>


</fieldset>

BookingMVC/Views/Home/Picture.cshtml
@model BookingMVC.Models.RoomIndexModel
@{
    ViewBag.Title = "Pictures";
}

<table>


    <tr>
        <th> @Html.DisplayNameFor(model => model.Photos)</th>
    </tr>
    @foreach (var item in Model.Photos)
    {
        <tr>

            <td>
                @{
                    var base64 = Convert.ToBase64String(item.Photo);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                }

                <img class="mySlides" src='@imgSrc' style="width:1000px; height:750px" />


            </td>

        </tr>
    }
</table>

<button class="w3-button w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
<button class="w3-button w3-display-right" onclick="plusDivs(+1)">&#10095;</button>

<script>
    var slideIndex = 0;
    showDivs(slideIndex);

    function plusDivs(n) {
        showDivs(slideIndex += n);
    }

    function showDivs(n) {
        var i;
        var x = document.getElementsByClassName("mySlides");
        if (n > x.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = x.length };
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        x[slideIndex - 1].style.display = "block";
    }
</script>