BookingMVC/Controllers/FeedbackController.cs
using BookingMVC.Common;
using BookingMVC.Filters;
using BookingMVC.Models;
using BookingMVC.Services.ContractsServices;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BookingMVC.Controllers
{
    [Authentication]
    public class FeedbackController : Controller
    {
        private IFeedbackService _feedbackService;
        public FeedbackController(IFeedbackService feedbackService)
        {
            _feedbackService = feedbackService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var feedbacks = _feedbackService.Get().Result;
            return View(feedbacks);
        }
        
        [HttpPost]
        public ActionResult Index(string search)
        {
            var feedbacks = _feedbackService.GetByUserName(search).Result;
            return View(feedbacks);
        }

        [HttpGet]
        public JsonResult Search(string search)
        {
            var names = _feedbackService.Search(search).Result;
            return Json(names, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Create(int userId, string userName)
        {
            ViewBag.UserId = userId;
            ViewBag.UserName = userName;
            return View();
        }

        [HttpPost]
        public ActionResult Create(FeedbackModel feedbackModel)
        {
            _feedbackService.Create(feedbackModel);
            return View(feedbackModel);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            ViewBag.EditMode = true;
            var feedback = _feedbackService.GetById(id).Result;
            ViewBag.UserId = feedback.UserId;
            ViewBag.UserName = feedback.Name;
            return View("Create", feedback);
        }
        
        [HttpPost]
        public ActionResult Edit(Feedback feedback)
        {
            _feedbackService.Edit(feedback);
            return View("Create", feedback);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            _feedbackService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

BookingMVC/Views/Feedback/Create.cshtml
@using BookingMVC.Models
@model FeedbackModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<form id="form1" method="post" style="text-align:center">
    <div>
        @Html.LabelFor(model => model.Description)
        @Html.EditorFor(model => model.Description)
    </div><br />
    <br />
    <span id="errorMessage" class="text-danger"></span>
    <span id="successMessage" class="text-success"></span>

    <br />
    <div><input type="button" value="Submit" onclick="FeedbackModel()" /></div>
    @if (Model != null)
    {
        <div><input type="hidden" id="id" name="id" value="@Model.Id" /></div>
    }
    <div><input type="hidden" id="userId" name="userId" value="@ViewBag.UserId" /></div>
    <div><input type="hidden" id="userName" name="userName" value="@ViewBag.UserName" /></div>
</form>


<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script type="text/javascript">
    var editMode = "@ViewBag.EditMode";
    function FeedbackModel() {

        var FeedbackModel = {};
        FeedbackModel.userId = $('#userId').val();
        FeedbackModel.description = $("#Description").val();
        FeedbackModel.name = $('#userName').val();
        FeedbackModel.id = $('#id').val();

        if (editMode.toLocaleLowerCase() == "true")
        {
            url = "@Url.Action("Edit")";
            method = 'POST';
        }
        else
        {
            url = "@Url.Action("Create")";
            method = 'POST';
        }
        $.ajax({
            url: url,
            method: method,
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(FeedbackModel),
            success: function (data) {
                $("#successMessage").fadeIn().html("Saved successfully");
            },
            error: function (msg) {
                $("#errorMessage").fadeIn().html("Saved");
            }
        })
    }
</script>

BookingMVC/Views/Feedback/Index.cshtml
@using BookingMVC.Models
@model IEnumerable<FeedbackModel>
@{
    ViewData["Title"] = "";
}

<h1>Index</h1>
<fieldset>

    @using (Html.BeginForm("Index", "Feedback", FormMethod.Post))
    {
        <b>
            Search Option:
            @Html.TextBox("Search", null, new { @class = "Search" })

            <input type="submit" name="submit" value="Search" />
        </b>
    }

    <legend style="text-align:center"><i>Feedbacks</i></legend>
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <table class="table" style="background-color:#b2dbcb">
        <tr style="background-color:#2ea764">
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <th>@Html.DisplayNameFor(model => model.DateTime)</th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <td>@Html.DisplayFor(model => item.Name) </td>
                <td>@Html.DisplayFor(model => item.Description)</td>
                <td>@Html.DisplayFor(model => item.DateTime)</td>

                <td> <input type="button" value="Edit" onclick="location.href= '@Url.Action("Edit", "Feedback", new { id = item.Id })'" style="border-color:black; border-width:1px" /></td>
                <td> <input type="button" value="Delete" onclick="location.href= '@Url.Action("Delete", "Feedback", new { id = item.Id })'" style="border-color:black; border-width:1px" /></td>

            </tr>
        }

    </table>
</fieldset>

@section Scripts{

    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
    <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css"
          rel="Stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#Search").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '../Feedback/Search',
                        data: { search: request.term },
                        dataType: "json",
                        type: "GET",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item.Name;
                            }))
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        },
                    });
                },
            })
        });
    </script>
}